config/routes.rb
Rails.application.routes.draw do
  
  get 'import_file' , to: "files#new" , as: "import_file"
  resources :orders, only: [:index]
  resources :files, only: [:index, :create]
  root to: "orders#index"
end

app/models/address.rb
class Address < ActiveRecord::Base
	has_many :orders
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
end

app/models/file_log.rb
class FileLog < ActiveRecord::Base
	attr_accessor :file

  validate :validate_file
  
  validates_presence_of :file, message: "Por favor selecione um arquivo."
 	
  private

  def validate_file
  	errors.add(:file , "Formato de arquivo inválido. O Aquivo precisa ser .txt") if self.file.present? and self.file.content_type != "text/plain"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :address
  belongs_to :provider
  belongs_to :product

  validates_presence_of :customer_id, message: "O cliente não pode ficar em branco"
  validates_presence_of :amount, message: "A quantidade não pode ficar em branco"
  validates_presence_of :unit_price, message: "O preço unitário não pode ficar em branco"
  validates_presence_of :address_id, message: "O endereço não pode ficar em branco"
  validates_presence_of :provider_id, message: "O fornecedor não pode ficar em branco"
  validates_presence_of :product_id, message: "O produto não pode ficar em branco"
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def run_rake(task, options = {})
	  options[:rails_env] ||= Rails.env
	  args = options.map { |n, v| "#{n.to_s.upcase}='#{v}'" }
	  system "/usr/bin/rake #{task} #{args.join(' ')} --trace 2>&1 >> #{Rails.root}/log/rake.log &"
	end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
	def index
		@files = FileLog.all 	
	end

	def new
		@file = FileLog.new
	end

	def create
		@file = FileLog.new(set_params) 

		if !set_params["file"].nil?
			original_file = params[:file_log][:file]
			@file.original_filename = original_file.original_filename
			time = Time.now
			@file.name = "#{rand(10000)}-#{original_file.original_filename}"
			@file.content_type = original_file.content_type
		end
		
		if @file.save			
			
			#Cria uma arquivo no tmp para ser processado em backgound
			File.open(Rails.root.join("tmp", @file.name ), "wb") do |file|
				file.write(original_file.read)
			end

			run_rake("fileprocess:execute")
			flash[:notice] = "Arquivo importado com sucesso. Em alguns minutos será importado para o banco de dados"
			redirect_to files_url
		else
			render :new
		end
	end

	private
	def set_params
		if params[:file_log].nil?
			return {"file" => nil}
		else
		 return params.require(:file_log).permit(:file)
		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	@orders = Order.paginate(:page => params[:page], :per_page => 30)
  	@total = [0.0, 0]
  	Order.all.map{ |order| @total[0] += (order.amount.to_f * order.unit_price.to_f); @total[1] += 1 }
  	@total_customers = Customer.count
  	@total_products = Product.count
  	@total_providers = Provider.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def total(quantity, price)
		quantity * price
	end

	def currency(value)
		value.to_s.gsub('.', ',')
	end

	def date_time(value)
		value.strftime("%d/%m/%Y - %H:%M")
	end
end

app/helpers/files_helper.rb
module FilesHelper
	def processed?(value)
		value == true ? "Processado" : image_tag("progress.gif", size: "150x30")
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/files/index.html.erb
<h3>Arquivos já importados</h3>
<div class="row">
	<div class="col-sm-12 col-md-9">
		<div class="col-sm-12 sidebox">
			<table class="table table-hover table-nowrap">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Data de importação</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					<% @files.each do |file| %>
						<tr>
							<td><%= file.original_filename %></td>
							<td><%= date_time(file.created_at) %></td>
							<td><%= processed?(file.processed) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-sm-12 col-md-3">
		<div class="col-sm-12 sidebox sidebox-button">
			<div class="sidebox-button text-center">
				<%= link_to "Importar um arquivo" , import_file_url , :class => "btn btn-lg btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/files/new.html.erb
<h3>Importar arquivo</h3>

<%= form_for(@file, url: files_url ,  html: {multpart: true , :class => "form"}, method: :post) do |f| %>
	<p>Por favor selecione um arquivo e depois clique em importar </p>

	<div class="form-group">
		<%= f.file_field :file, :class => "form-control" %>
		<%= @file.errors[:file][0] %>
	</div>
	<%= link_to "Voltar", files_url , :class => "btn btn-md btn-primary" %>
	<%= f.submit "Enviar" , :class => "btn btn-md btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avaliacao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ORDENS", root_url, :class=>"navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Ordens", root_path %></li>
        <li><%= link_to "Importação", files_path %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sobre", "https://github.com/jeffersonsc/avaliacao" %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<section class="my-continer">
	<%= yield %>	
</section>

</body>
</html>

app/views/orders/index.html.erb
<h3>Lançamentos</h3>
<div class="row">
	<div class="col-sm-12 col-md-9">
		<div class="col-sm-12 sidebox">
			<table class="table table-striped table-hover table-nowrap">
				<thead>
					<tr>
						<th>Cliente</th>
						<th>Descrição</th>
						<th>Preço uni.</th>
						<th>Quantidade</th>
						<th>Endereço</th>
						<th>Fonecedor</th>
						<th>Criado em</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<% @orders.each do |order| %>
						<tr>
							<td> <%= order.customer.name %> </td>
							<td> <%= order.product.name %> </td>
							<td> R$ <%= currency(order.product.price) %> </td>
							<td> <%= order.amount %> </td>
							<td> <%= order.address.street %> </td>
							<td> <%= order.provider.name %> </td>
							<td> <%= date_time(order.created_at) %></td>
							<td>
								R$ <%= currency(total(order.amount, order.unit_price)) %>
							</td>
						</tr>
					<% end %>
				</tbody>
				<tfoot>
					<tr>
						<th colspan="7"><span class="pull-right">Total</span></th>
						<td id="total_gross">R$ <%= @total[0] %></td>
					</tr>
				</tfoot>
			</table>

			<%= will_paginate(@orders) %>
		</div>
	</div>	
	<div class="col-sm-12 col-md-3">
		<div class="col-sm-12 sidebox sidebox-button">
			<h5>Informações gerais</h5>
			<p> - Total de clientes castrados: <%= @total_customers.to_i %></p>
			<p> - Total de produtos cadatrados: <%= @total_products.to_i %></p>
			<p> - Total de fornecedores cadatrados: <%= @total_providers.to_i %></p>
			<p> - Total de ordens cadastradas: <%= @total[1] %></p>

			<h5> Total bruto <%= @total[0].round(2) %> </h5>
		</div>
		<div class="col-sm-12 sidebox sidebox-button">
			<div class="sidebox-button text-center">
				<%= link_to "Importar um arquivo" , import_file_url , :class => "btn btn-lg btn-primary" %>
			</div>
		</div>
	</div>
</div>